spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 设置实例元数据
        #metadata:
          #instance: d
          #haha: hehe
          #version: v1
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center
server:
  port: 8085