spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定namespace
        namespace: 41e75d7f-a117-4bf5-8ab7-5e62850cbf0d
        # 指定集群名称
        # NJ 假设南京机房
        cluster-name: NJ
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: contner-center
server:
  port: 8081

# 基于配置的ribbon
user-center:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #NFLoadBalancerRuleClassName: com.wanggs.alibaba.configuration.NacosWeightRandomV2Rule
    NFLoadBalancerRuleClassName: com.wanggs.alibaba.configuration.NacosSameClusterWeightedRule
# Ribbon配置饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    com.wanggs: debug # com.wanggs包里面的所有日志都会以debug级别输出
    com.wanggs.alibaba.feignclient.UserCenterFeignClient: debug # 指定输出级别