spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定namespace
        namespace: 41e75d7f-a117-4bf5-8ab7-5e62850cbf0d
        # 指定集群名称
        # NJ 假设南京机房
        cluster-name: NJ
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: contner-center
  boot:
    admin:
      client:
        url: http://127.0.0.1:8002
        username: admin
        password: gbw@123456
        instance:
          prefer-ip: true
server:
  port: 8081

# 基于配置的ribbon
user-center:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #NFLoadBalancerRuleClassName: com.wanggs.alibaba.configuration.NacosWeightRandomV2Rule
    NFLoadBalancerRuleClassName: com.wanggs.alibaba.configuration.NacosSameClusterWeightedRule
# Ribbon配置饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    com: debug
  file:
    path: spring/log

feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full

#启用监控.开启监控后，可直接通过actuator的rest接口查看服务的详细信息。例如查看网关的路由：http://localhost:8888/actuator/gateway/routes
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 开放所有端点health，info，metrics，通过actuator/+端点名就可以获取相应的信息。默认打开health和info
  endpoint:
    health:
      show-details: always  #未开启actuator/health时，我们获取到的信息是{"status":"UP"}，status的值还有可能是 DOWN。开启后打印详细信息
    shutdown:
      enabled: true #远程关闭或者重启服务